// AUTO-GENERATED by ViPERDSP/tools/viper_layout_gen.py
// DO NOT EDIT MANUALLY. Regenerate this file after
// any change to `ViPERDSP/include/ViPERParams.h`.
//
// Mirrors viper::ViPERParams byte layout sent through typed
// parameter dispatch. Field offsets are derived from the same C++
// header the AIDL HAL consumer compiles against — Kotlin and C++
// cannot disagree on struct shape.
package com.llsl.viper4android.viper

object ViperParamsLayout {
    // Root struct: viper::ViPERParams
    const val SIZE: Int = 1144
    const val MASTER_LIMITER: Int = 0
    const val PLAYBACK_GAIN_CONTROL: Int = 12
    const val LUFS: Int = 28
    const val FET_COMPRESSOR: Int = 44
    const val BASS: Int = 112
    const val BASS_MONO: Int = 132
    const val PSYCHOACOUSTIC_BASS: Int = 152
    const val SPECTRUM_EXTENSION: Int = 172
    const val EQUALIZER: Int = 184
    const val CONVOLVER: Int = 316
    const val DDC: Int = 324
    const val FIELD_SURROUND: Int = 328
    const val DIFF_SURROUND: Int = 344
    const val STEREO_IMAGER: Int = 364
    const val HEADPHONE_SURROUND: Int = 388
    const val REVERB: Int = 396
    const val DYNAMIC_SYSTEM: Int = 420
    const val CLARITY: Int = 452
    const val CURE: Int = 464
    const val TUBE_SIMULATOR: Int = 472
    const val ANALOG_X: Int = 476
    const val SPEAKER_CORRECTION: Int = 484
    const val MULTIBAND_COMPRESSOR: Int = 488
    const val DYNAMIC_EQ: Int = 856

    object MasterLimiter {
        const val SIZE: Int = 12
        const val THRESHOLD: Int = 0
        const val OUTPUT_VOLUME: Int = 4
        const val CHANNEL_PAN: Int = 8
    }

    object PlaybackGainControl {
        const val SIZE: Int = 16
        const val ENABLE: Int = 0
        const val STRENGTH: Int = 4
        const val MAX_GAIN: Int = 8
        const val OUTPUT_THRESHOLD: Int = 12
    }

    object Lufs {
        const val SIZE: Int = 16
        const val ENABLE: Int = 0
        const val TARGET: Int = 4
        const val MAX_GAIN: Int = 8
        const val SPEED: Int = 12
    }

    object FetCompressor {
        const val SIZE: Int = 68
        const val ENABLE: Int = 0
        const val THRESHOLD: Int = 4
        const val RATIO: Int = 8
        const val KNEE: Int = 12
        const val KNEE_AUTO: Int = 16
        const val GAIN: Int = 20
        const val GAIN_AUTO: Int = 24
        const val ATTACK: Int = 28
        const val ATTACK_AUTO: Int = 32
        const val RELEASE: Int = 36
        const val RELEASE_AUTO: Int = 40
        const val KNEE_MULTI: Int = 44
        const val MAX_ATTACK: Int = 48
        const val MAX_RELEASE: Int = 52
        const val CREST: Int = 56
        const val ADAPT: Int = 60
        const val NO_CLIP: Int = 64
    }

    object Bass {
        const val SIZE: Int = 20
        const val ENABLE: Int = 0
        const val MODE: Int = 4
        const val FREQUENCY: Int = 8
        const val GAIN: Int = 12
        const val ANTI_POP: Int = 16
    }

    object BassMono {
        const val SIZE: Int = 20
        const val ENABLE: Int = 0
        const val MODE: Int = 4
        const val FREQUENCY: Int = 8
        const val GAIN: Int = 12
        const val ANTI_POP: Int = 16
    }

    object PsychoacousticBass {
        const val SIZE: Int = 20
        const val ENABLE: Int = 0
        const val CUTOFF: Int = 4
        const val INTENSITY: Int = 8
        const val HARMONIC_ORDER: Int = 12
        const val ORIGINAL_LEVEL: Int = 16
    }

    object SpectrumExtension {
        const val SIZE: Int = 12
        const val ENABLE: Int = 0
        const val STRENGTH: Int = 4
        const val EXCITER: Int = 8
    }

    object Equalizer {
        const val SIZE: Int = 132
        const val ENABLE: Int = 0
        const val BAND_COUNT: Int = 4
        const val BAND_LEVELS: Int = 8
        const val BAND_LEVELS_LEN: Int = 31
    }

    object Convolver {
        const val SIZE: Int = 8
        const val ENABLE: Int = 0
        const val CROSS_CHANNEL: Int = 4
    }

    object Ddc {
        const val SIZE: Int = 1
        const val ENABLE: Int = 0
    }

    object FieldSurround {
        const val SIZE: Int = 16
        const val ENABLE: Int = 0
        const val WIDENING: Int = 4
        const val MID_IMAGE: Int = 8
        const val DEPTH: Int = 12
    }

    object DiffSurround {
        const val SIZE: Int = 20
        const val ENABLE: Int = 0
        const val DELAY: Int = 4
        const val REVERSE: Int = 8
        const val WET_DRY_MIX: Int = 12
        const val LP_CUTOFF: Int = 16
    }

    object StereoImager {
        const val SIZE: Int = 24
        const val ENABLE: Int = 0
        const val LOW_WIDTH: Int = 4
        const val MID_WIDTH: Int = 8
        const val HIGH_WIDTH: Int = 12
        const val LOW_CROSSOVER: Int = 16
        const val HIGH_CROSSOVER: Int = 20
    }

    object HeadphoneSurround {
        const val SIZE: Int = 8
        const val ENABLE: Int = 0
        const val QUALITY: Int = 4
    }

    object Reverb {
        const val SIZE: Int = 24
        const val ENABLE: Int = 0
        const val ROOM_SIZE: Int = 4
        const val WIDTH: Int = 8
        const val DAMP: Int = 12
        const val WET: Int = 16
        const val DRY: Int = 20
    }

    object DynamicSystem {
        const val SIZE: Int = 32
        const val ENABLE: Int = 0
        const val X_COEFF_LOW: Int = 4
        const val X_COEFF_HIGH: Int = 8
        const val Y_COEFF_LOW: Int = 12
        const val Y_COEFF_HIGH: Int = 16
        const val SIDE_GAIN_LOW: Int = 20
        const val SIDE_GAIN_HIGH: Int = 24
        const val STRENGTH: Int = 28
    }

    object Clarity {
        const val SIZE: Int = 12
        const val ENABLE: Int = 0
        const val MODE: Int = 4
        const val GAIN: Int = 8
    }

    object Cure {
        const val SIZE: Int = 8
        const val ENABLE: Int = 0
        const val CROSSFEED_PRESET: Int = 4
    }

    object TubeSimulator {
        const val SIZE: Int = 1
        const val ENABLE: Int = 0
    }

    object AnalogX {
        const val SIZE: Int = 8
        const val ENABLE: Int = 0
        const val MODE: Int = 4
    }

    object SpeakerCorrection {
        const val SIZE: Int = 1
        const val ENABLE: Int = 0
    }

    object MultibandCompressorBand {
        const val SIZE: Int = 68
        const val ENABLE: Int = 0
        const val THRESHOLD: Int = 4
        const val RATIO: Int = 8
        const val KNEE: Int = 12
        const val KNEE_AUTO: Int = 16
        const val GAIN: Int = 20
        const val GAIN_AUTO: Int = 24
        const val ATTACK: Int = 28
        const val ATTACK_AUTO: Int = 32
        const val RELEASE: Int = 36
        const val RELEASE_AUTO: Int = 40
        const val KNEE_MULTI: Int = 44
        const val MAX_ATTACK: Int = 48
        const val MAX_RELEASE: Int = 52
        const val CREST: Int = 56
        const val ADAPT: Int = 60
        const val NO_CLIP: Int = 64
    }

    object MultibandCompressor {
        const val SIZE: Int = 368
        const val ENABLE: Int = 0
        const val BAND_COUNT: Int = 4
        const val CROSSOVER_FREQUENCIES: Int = 8
        const val CROSSOVER_FREQUENCIES_LEN: Int = 5
        const val BANDS: Int = 28
        const val BANDS_LEN: Int = 5
    }

    object DynamicEqBand {
        const val SIZE: Int = 28
        const val FREQUENCY: Int = 0
        const val Q: Int = 4
        const val GAIN: Int = 8
        const val THRESHOLD: Int = 12
        const val ATTACK: Int = 16
        const val RELEASE: Int = 20
        const val FILTER_TYPE: Int = 24
    }

    object DynamicEq {
        const val SIZE: Int = 288
        const val ENABLE: Int = 0
        const val BAND_COUNT: Int = 4
        const val BANDS: Int = 8
        const val BANDS_LEN: Int = 10
    }
}
